"""Treasury transfer data models.

``TransferProposal`` (a proposed exchange↔bank movement) and
``TransferResult`` (the outcome of an executed transfer) — the domain
types the Harvester produces / consumes.

There is deliberately no ``HarvesterPort`` abstraction: per ADR-004 the
Harvester is a *service* (``services/harvester.py``) that withdraws via
Kraken's API through ``ExchangePort``, not a swappable adapter behind a
port. (A speculative ``HarvesterPort`` ABC lived here through Phase 4 but
nothing ever implemented / injected it — removed 2026-06-03.)

CRITICAL: the Harvester is the ONLY module with withdrawal permissions.
All transfers must respect strict thresholds and safety caps.
"""

from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, Field

from wobblebot.domain.value_objects import Timestamp


class TransferProposal(BaseModel):
    """Proposal for a fund transfer.

    Generated by ``services.harvester.propose_transfer()`` based on balance
    thresholds. Persisted to ``transfer_proposals`` (Stage 4.3) for
    operator review; execution lands in Stage 4.4 behind the
    ``harvester.enabled`` gate.
    """

    proposal_id: str = Field(..., description="Unique proposal ID")
    direction: Literal["exchange_to_bank", "bank_to_exchange"]
    asset: str = Field(..., min_length=1, max_length=10)
    amount: Decimal = Field(..., gt=0)
    rationale: str = Field(..., description="Why this transfer is proposed")
    current_exchange_balance: Decimal = Field(..., ge=0)
    target_exchange_balance: Decimal = Field(..., ge=0)
    created_at: Timestamp = Field(
        ...,
        description="When the proposal was generated (used for forensic ordering)",
    )


class TransferResult(BaseModel):
    """Result of an executed transfer.

    Persisted to ``transfer_results`` (Stage 4.4b) for the forensic
    audit chain + the rolling-24h day-cap computation. ``direction``
    and ``asset`` are denormalized from the originating
    ``TransferProposal`` so the day-cap query is single-table —
    avoids a join on every cycle of cli/harvest.
    """

    proposal_id: str
    transaction_id: str = Field(..., description="Exchange refid")
    status: Literal["pending", "completed", "failed"]
    executed_amount: Decimal = Field(..., ge=0)
    direction: Literal["exchange_to_bank", "bank_to_exchange"]
    asset: str = Field(..., min_length=1, max_length=10)
    timestamp: Timestamp = Field(..., description="When the transfer was submitted")
