"""HarvesterPort - Abstract interface for fund transfer management.

This port defines the contract for treasury management (Kraken ↔ bank).
The Harvester module implements this port (Phase 4+).

CRITICAL: Harvester is the ONLY module with withdrawal permissions.
All transfers must respect strict thresholds and safety caps.
"""

from abc import ABC, abstractmethod
from decimal import Decimal
from typing import Any, Literal

from pydantic import BaseModel, Field

from wobblebot.domain.value_objects import Timestamp


class TransferProposal(BaseModel):
    """Proposal for a fund transfer.

    Generated by Harvester based on balance thresholds.
    """

    proposal_id: str = Field(..., description="Unique proposal ID")
    direction: Literal["kraken_to_bank", "bank_to_kraken"]
    asset: str = Field(..., min_length=1, max_length=10)
    amount: Decimal = Field(..., gt=0)
    rationale: str = Field(..., description="Why this transfer is proposed")
    current_kraken_balance: Decimal = Field(..., ge=0)
    target_kraken_balance: Decimal = Field(..., ge=0)


class TransferResult(BaseModel):
    """Result of an executed transfer."""

    proposal_id: str
    transaction_id: str = Field(..., description="Exchange/bank transaction ID")
    status: Literal["pending", "completed", "failed"]
    executed_amount: Decimal = Field(..., ge=0)
    timestamp: Timestamp = Field(..., description="When the transfer settled")


class HarvesterPort(ABC):
    """Abstract interface for fund transfer management.

    Phase 4+ feature - manages Kraken ↔ bank transfers.

    Implementations:
    - Harvester module (uses Kraken withdrawal API per ADR-004)
    """

    @abstractmethod
    async def check_balance_status(self, asset: str) -> TransferProposal | None:
        """Check if a transfer is needed based on thresholds.

        Args:
            asset: Asset to check (e.g., USD)

        Returns:
            Transfer proposal if action needed, None otherwise

        Raises:
            HarvesterError: If balance check fails
        """
        pass

    @abstractmethod
    async def execute_transfer(self, proposal: TransferProposal) -> TransferResult:
        """Execute an approved transfer.

        CRITICAL: Only call after Orchestrator approval and safety validation.

        Args:
            proposal: Approved transfer proposal

        Returns:
            Transfer result with transaction ID and status

        Raises:
            HarvesterError: If transfer fails
            SafetyViolation: If proposal violates safety caps
        """
        pass

    @abstractmethod
    async def get_transfer_history(self, limit: int = 100) -> list[TransferResult]:
        """Get history of executed transfers.

        Args:
            limit: Maximum number of results

        Returns:
            List of transfer results

        Raises:
            HarvesterError: If history cannot be retrieved
        """
        pass

    @abstractmethod
    async def get_configured_thresholds(self, asset: str) -> dict[str, Any]:
        """Get configured balance thresholds for an asset.

        Args:
            asset: Asset code

        Returns:
            Dict with min_liquidity, max_surplus, top_up_amount, etc.

        Raises:
            HarvesterError: If thresholds cannot be retrieved
        """
        pass
